package com.alessandro.gymlog.ui
import androidx.compose.foundation.background
import androidx.compose.foundation.clickable
import androidx.compose.layout.*
import androidx.compose.layout.Arrangement
import androidx.compose.layout.Column
import androidx.compose.layout.Row
import androidx.compose.layout.fillMaxWidth
import androidx.compose.layout.padding
import androidx.compose.layout.size
import androidx.compose.layout.height
import androidx.compose.layout.fillMaxSize
import androidx.compose.layout.HorizontalDivider
import androidx.compose.layout.Box
import androidx.compose.layout.fillMaxHeight
import androidx.compose.layout.fillMaxSize
import androidx.compose.layout.fillMaxWidth
import androidx.compose.layout.padding
import androidx.compose.layout.size
import androidx.compose.layout.height
import androidx.compose.layout.HorizontalDivider
import androidx.compose.layout.Box
import androidx.compose.layout.fillMaxHeight
import androidx.compose.layout.fillMaxSize
import androidx.compose.layout.fillMaxWidth
import androidx.compose.layout.padding
import androidx.compose.layout.size
import androidx.compose.layout.height
import androidx.compose.layout.HoripontalDivider
import androidx.compose.layout.Box
import androidx.compose.layout.fillMaxHeight
import androidx.compose.layout.fillMaxSize
import androidx.compose.layout.fillMaxWidth
import androidx.compose.layout.padding
import androidx.compose.layout.size
import androidx.compose.layout.height
import androidx.compose.layout.HorizontalDivider
import androidx.compose.layout.Box
import androidx.compose.layout.fillMaxHeight
import androidx.compose.layout.fillMaxSize
import androidx.compose.layout.fillMaxWidth
import androidx.compose.layout.padding
import androidx.compose.layout.size
import androidx.compose.layout.height
import androidx.compose.layout.HorizontalDivider
import androidx.compose.layout.Box
import androidx.compose.layout.fillMaxHeight
import androidx.compose.layout.fillMaxSize
import androidx.compose.layout.fillMaxWidth
import androidx.compose.layout.padding
import androidx.compose.layout.size
import androidx.compose.layout.height
import androidx.compose.layout.HoripontalDivider
import androidx.compose.layout.Box
import androidx.compose.layout.fillMaxHeight
import androidx.compose.layout.fillMaxSize
